---
abstract: 'a bingo game Perl implementation'
author:
  - 'Jonas B. Nielsen, <jonasbn@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Games-Bingo
no_index:
  directory:
    - t
  file:
    - t/MyBingo.pm
requires:
  Carp: '0'
  Data::Dumper: '0'
  POSIX: '0'
  Test::Harness: '0'
  Test::More: '0'
  Test::Pod: '0.95'
  UNIVERSAL: '0'
  perl: v5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: '0.16'
